stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: openjdk:19-jdk
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  image: openjdk:19-jdk
  script:
    - ./gradlew clean test jacocoTestReport check
  dependencies:
    - build
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
      - build/reports/jacoco/test/jacocoTestReport.xml
    expire_in: 1 day

coverage:
  stage: test
  image: openjdk:19-jdk
  script:
    - apt-get update && apt-get install -y xargs
    - ./gradlew test jacocoTestReport jacocoTestCoverageVerification
  dependencies:
    - test

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t my-app .
    - docker run -d --name my-app-container --network practice-bot-network my-app
    - docker ps
    - docker logs my-app-container
  only:
    - main
  when: manual