stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: openjdk:19-jdk
  script:
    - ./gradlew --no-daemon clean shadowJar
  artifacts:
    paths:
      - build/libs/*.jar

build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-app:latest .
  artifacts:
    paths:
      - Dockerfile
  only:
    - main

test:
  stage: test
  image: openjdk:19-jdk
  services:
    - name: postgres:latest
      alias: postgres
  variables:
    POSTGRES_DB: testdb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    PG_DSN: "jdbc:postgresql://postgres:5432/testdb?user=postgres&password=postgres"
    BOT_TOKEN: "some_token"
  script:
    - ./gradlew clean test jacocoTestReport check
  dependencies:
    - build
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
      - build/reports/jacoco/test/jacocoTestReport.xml
    expire_in: 1 day

coverage:
  stage: test
  image: openjdk:19-jdk
  services:
    - name: postgres:latest
      alias: postgres
  variables:
    POSTGRES_DB: testdb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    PG_DSN: "jdbc:postgresql://postgres:5432/testdb?user=postgres&password=postgres"
    BOT_TOKEN: "some_token"
  allow_failure: true
  script:
    - apt-get update && apt-get install -y xargs
    - ./gradlew test jacocoTestReport jacocoTestCoverageVerification
  dependencies:
    - test

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying Docker container"
    - docker rm -f my-app-container || true
    - docker run -d --name my-app-container -e BOT_TOKEN=$BOT_TOKEN -e PG_DSN=$PG_DSN my-app:latest
  only:
    - main
  dependencies:
    - build-image
