stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: openjdk:19-jdk
  script:
    - ./gradlew --no-daemon clean shadowJar
  artifacts:
    paths:
      - build/libs/*.jar

build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-app:latest .
  artifacts:
    paths:
      - Dockerfile

test:
  stage: test
  image: openjdk:19-jdk
  script:
    - ./gradlew clean test jacocoTestReport check
  dependencies:
    - build
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
      - build/reports/jacoco/test/jacocoTestReport.xml
    expire_in: 1 day

coverage:
  stage: test
  image: openjdk:19-jdk
  allow_failure: true
  script:
    - apt-get update && apt-get install -y xargs
    - ./gradlew test jacocoTestReport jacocoTestCoverageVerification
  dependencies:
    - test

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying Docker container"
    - docker rm -f my-app-container || true
    - docker run --name my-app-container -e BOT_TOKEN=$BOT_TOKEN -e PG_DSN=$PG_DSN my-app:latest
  only:
    - main
  dependencies:
    - build-image
