services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practice_bot
    restart: unless-stopped
    ports:
      - "5555:5432"
    expose:
      - 5432
    networks:
      - practice-bot-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d practice_bot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      BOT_TOKEN: $BOT_TOKEN
      PG_DSN: $PG_DSN
      INN_CHECK: $INN_CHECK
    restart: unless-stopped
    networks:
      - practice-bot-network

networks:
  practice-bot-network:
    driver: bridge